### ISSUE TITLE
suggestion: command line interface for batch processing

### ISSUE THREAD

**Issue by ChrisNbg** [rcmaehl/WhyNotWin11#106]
Hello,

you made a interesting and good working tool. My idea was to make a batch script to test all computers of an entire organisation,

So it would be cool if you are able to make some improovments here. perhaps you can make some commandline Options like /cli to give output only on cli or something to format the output 
/txt --> write an formatet text to the terminal or a file
/csv --> write an comma seperated line and append append it to a file...

thanks in advance from Germany and greets to Kentucky
Christian Rech

**Comment by micwoj92** [comment]
Kinda duplicate, but it is first separate issue, so I will leave it.

**Comment by rcmaehl** [comment]
It's currently 2AM as I write this.

I'd like to apologize to any Systems Automation Engineers, SysAdmins, and other IT reps that are looking at getting this used for batch processing, SCCM deployment, and other environment checks for my slow progress on this issue.

The only issue right now is getting /format to work with GUI output. I just can't logic right now even with caffeine. I'll try to get this done sometime after my main job, likely the afternoon US ET for ~2.3.1.

Issues you might encounter in ~2.3.1 that should be fixed in ~2.3.2:
* [ ] #50 - SnapDragon/Microsoft Processors can cause the Architecture Check to report 32 bit which is a "fail". This will likely be on of the first issues fixed in ~2.3.2.
* [ ] #58 - DirectX results are based on Enabled DirectX Version, not hardware support
* [ ] #116 - Screen Resolution is not checked (Win11 requires 720p minimum, but even 4:3 monitors from mid 2000s should meet this)
* [ ] #162 - For Machines with Multiple Boot Drives, all must pass GPT check currently

I know some of you may support significantly older environments, so it should be noted the application will give incorrect results on Windows 7 (or earlier), this is a likely `Won't Fix` issue but I can be persuaded otherwise.

**Comment by rcmaehl** [comment]
Hi Sysadmins, 

This is pretty much good to go. I'm investigating some issues with the exit code, so I wouldn't use /silent without /format right now. CSV output detects existing files and will append. TXT output will always override. This may be changed in the future and feedback is much appreciated.

**Comment by micwoj92** [comment]
@rcmaehl Can this be closed? 2.4.0.0 supports command line
