### ISSUE TITLE
3.0 meta issue

### ISSUE THREAD

**Issue by micwoj92** [rcmaehl/WhyNotWin11#48]
* [ ] Fully implement high contrast (#4)
* [ ] Add command line switches for IT admins
* [ ] Add social buttons for PayPal GitHub and more
* [ ] Add note for hiring
* [ ] Add Backup GPT formatting check (#29)
* [ ] Add Scan Result Summary (#32)
* [ ] Make Checks Non-Blocking (#39)

**Comment by micwoj92** [comment]
Is the note for hiring working? Then it could also be checked as done.

**Comment by micwoj92** [comment]
updated so it covers all issues from milestone

**Comment by rcmaehl** [comment]
> updated so it covers all issues from milestone

Can you make `Command Line Switches` a sub item of #39

**Comment by micwoj92** [comment]
![image](https://user-images.githubusercontent.com/45581170/123551606-d4b7f000-d772-11eb-8ff5-4baee6cfdb3a.png)
this is what you meant?

**Comment by rcmaehl** [comment]
Thanks!
